feat : 질문하기 UI 구현
Nexters/draw-frontend pull request #17
Opened 2023-07-24 07:48 UTC by 9yujin

- MBTI picker 양쪽 선택 가능하도록 기능 추가했는데, 그 과정에서 코드가 많이 더러워짐... 리뷰 미리 감사함둥ㅎㅎㅠ

2023-07-24 13:16 UTC, Puterism requested changes
질문해준 내용에 답변만 해주면 바로 어프루브할게! 수고 많았어 👍

2023-07-24 13:16 UTC, Puterism commented on src/pages/NewQuestion/NewQuestion.styles.ts
> +  height: 100svh;
```suggestion
  height: 100vh;
  height: 100svh;
```

fallback 스타일링이 필요해요

2023-07-24 13:16 UTC, Puterism commented on src/pages/NewQuestion/components/OptionSelect/OptionSelect.styles.ts
> +  height: 100svh;
```suggestion
  height: 100vh;
  height: 100svh;
```

여기도 fallback 스타일링이 필요해요!

2023-07-24 13:16 UTC, Puterism commented on src/pages/NewQuestion/components/OptionPreview/OptionPreview.tsx
> +      <RemoveOption />
개인적으로 아이콘 컴포넌트 뒤에는 Icon이라는 suffix를 붙이는 걸 선호하는 편이야. (e.g. `<RemoveOptionIcon />`)
그 이유는 해당 컴포넌트가 일반적인 컴포넌트인지 아닌지 구분하기가 어려워지기 때문이야.
다만, 취향의 영역이기 때문에 반영 여부는 선택사항으로 남겨둘게!

2023-07-24 13:16 UTC, Puterism commented on src/pages/NewQuestion/NewQuestion.tsx
> +  const [isOptionSelectOpen, setISOptionSelectOpen] = useState(false);
```suggestion
  const [isOptionSelectOpen, setIsOptionSelectOpen] = useState(false);
```

오타가 있는 듯!

2023-07-24 13:16 UTC, Puterism commented on src/components/MBTIPicker/MultiMBTIPicker.tsx
> +const MultiMBTIPicker = ({ onChange, defaultValue }: MultiMBTIPickerProps) => {
나도 컴포넌트를 분리한 선택이 맞다고 생각해! 좋은 분리인 듯! 👍

2023-07-24 13:16 UTC, Puterism commented on src/components/MBTIPicker/MultiMBTIPicker.tsx
> +const MultiMBTIPicker = ({ onChange, defaultValue }: MultiMBTIPickerProps) => {
최대 4개까지 선택 가능하다고 쓰여 있는데, 8개 모두 선택 가능한 상태네.
근데 I와 E도 같이 선택이 가능한가? 정책을 확인해볼 필요가 있을 것 같아.

<img width="332" alt="스크린샷 2023-07-24 오후 10 08 43" src="https://github.com/Nexters/draw-frontend/assets/2542730/0cb5002d-947f-4cc8-96c5-7fc45a0ba1c3">

2023-07-24 13:16 UTC, Puterism commented on src/components/MBTIPicker/MultiMBTIPicker.tsx
> +  }, [selectedMBTI]);
이 코드는 왜 추가해두었어?

2023-07-24 13:16 UTC, Puterism commented on src/pages/NewQuestion/NewQuestion.tsx
> +              <Styled.AskOptionDescription>이런 사람에게 질문하고 싶어요!</Styled.AskOptionDescription>
focus 여부에 따라서 `이런 사람에게 질문하고 싶어요!`의 높이가 달라지는데 의도한 부분이 있어?

<img width="373" alt="스크린샷 2023-07-24 오후 10 11 55" src="https://github.com/Nexters/draw-frontend/assets/2542730/7a7c3e8c-77af-4320-9bbc-efe2b9efd92f">
<img width="371" alt="스크린샷 2023-07-24 오후 10 12 00" src="https://github.com/Nexters/draw-frontend/assets/2542730/c2fafdaf-e751-46d1-90e7-e90f03f267dc">

2023-07-24 13:16 UTC, Puterism commented on src/pages/NewQuestion/components/OptionSelect/OptionSelect.tsx
> +  mbtiState: [MultiMBTI, Dispatch<SetStateAction<MultiMBTI>>];
useState의 반환값을 통째로 prop으로 넘기면 어떤 문제가 있을까?
이렇게 작성할 수밖에 없는 상황이 존재한다고는 생각하지만, 나는 지양해야 하는 코드라고 생각해.
(지금은 꼭 고치지 않아도 돼!)

2023-07-24 13:16 UTC, Puterism commented on src/pages/NewQuestion/components/OptionSelect/OptionSelect.tsx
> +              <BinaryPicker
잘 가져다가 사용해주셔서 감사합니다 😄

2023-07-24 14:30 UTC, 9yujin commented on src/components/MBTIPicker/MultiMBTIPicker.tsx
> +const MultiMBTIPicker = ({ onChange, defaultValue }: MultiMBTIPickerProps) => {
아 이거 안그래도 영모가 피그마에 코멘트 달아놨던거!! 만약에 분류당 하나씩만 선택 가능하게 되면 4개선택제한을 굳이 걸 필요가 없으니까 일단 보류할겡

2023-07-24 14:32 UTC, 9yujin commented on src/pages/NewQuestion/NewQuestion.tsx
> +              <Styled.AskOptionDescription>이런 사람에게 질문하고 싶어요!</Styled.AskOptionDescription>
<img width="636" alt="스크린샷 2023-07-24 오후 11 32 11" src="https://github.com/Nexters/draw-frontend/assets/55226431/db471b1a-5a7a-4d48-9557-9c65427853e0">

디자인상에서 하단 시스템 탭바 영역 채우기 위해서 높이를 더 줬더라구

2023-07-24 14:49 UTC, 9yujin commented on src/components/MBTIPicker/MultiMBTIPicker.tsx
> +  }, [selectedMBTI]);
```typescript
const MultiMBTIPicker = ({ onChange, defaultValue }: MultiMBTIPickerProps) => {
  const [selectedMBTI, setSelectedMBTI] = useState<MultiMBTI>(defaultValue || []);

  const handleToggleSelect = (value: string) => {
    if (selectedMBTI.includes(value)) {
      setSelectedMBTI(selectedMBTI.filter((v) => v !== value));
    } else {
      setSelectedMBTI([...selectedMBTI, value]);
    }
  };

  useEffect(() => {
    onChange?.(selectedMBTI);
  }, [selectedMBTI]);
  ```
  컴포넌트 내부 상태가 바뀐다음에 외부에서 props으로 받은 onChange함수로 넘겨주려 했던건데, 더 좋은 방법이 있을까?

2023-07-24 15:20 UTC, 9yujin commented on src/pages/NewQuestion/components/OptionSelect/OptionSelect.tsx
> +  mbtiState: [MultiMBTI, Dispatch<SetStateAction<MultiMBTI>>];
상태 값과 세터가 모두 하위컴포넌트에서 필요했었는데, 상태 값이 필요하지않도록 바꿔서, onChange함수만 전달하도록 수정했우!!
원래는 `flag &&`로 조건부렌더링을 시켜놔서 매번 새로 선택된값을 기본값으로 넣어주어야 했는데, 이젠 그냥 아래에 내려만 두고 스크롤 못하도록?? 
근데 어떤게 더 좋은방법인지 잘 모르겟다

2023-07-25 11:15 UTC, Puterism commented
<img width="1063" alt="스크린샷 2023-07-25 오후 8 15 38" src="https://github.com/Nexters/draw-frontend/assets/2542730/5d65c64a-f607-4d6a-82aa-5b8812ef581b">

미사용 변수가 있어서 배포가 실패했으니 한 번 확인해줘.

2023-07-25 11:17 UTC, Puterism commented on src/pages/NewQuestion/NewQuestion.tsx
> +              <Styled.AskOptionDescription>이런 사람에게 질문하고 싶어요!</Styled.AskOptionDescription>
아하, 오키오키

2023-07-25 11:28 UTC, Puterism commented on src/components/MBTIPicker/MultiMBTIPicker.tsx
> +  }, [selectedMBTI]);
이렇게 하면 어떨까 싶어. 나는 onChange가 trigger되는 주체가 useEffect이면 안된다고 생각해.

```jsx
  const handleToggleSelect = (value: string) => {
    const nextSelectedMBTI = (() => {
      if (selectedMBTI.includes(value)) {
        return selectedMBTI.filter((v) => v !== value);
      }

      return [...selectedMBTI, value]
    })()

    setSelectedMBTI(nextSelectedMBTI);
    onChange?.(nextSelectedMBTI);
  };
```

2023-07-25 11:29 UTC, Puterism requested changes
리뷰 코멘트 하나 달아놨으니 확인해줘!

<img width="1063" alt="스크린샷 2023-07-25 오후 8 15 38" src="https://github.com/Nexters/draw-frontend/assets/2542730/5d65c64a-f607-4d6a-82aa-5b8812ef581b">

그리고 미사용 변수가 있어서 배포가 실패했으니 한 번 확인해줘.

2023-07-25 11:30 UTC, Puterism commented on src/pages/NewQuestion/components/OptionSelect/OptionSelect.tsx
> +  mbtiState: [MultiMBTI, Dispatch<SetStateAction<MultiMBTI>>];
수정한 코드는 확인했어!

> 원래는 flag &&로 조건부렌더링을 시켜놔서 매번 새로 선택된값을 기본값으로 넣어주어야 했는데,
이젠 그냥 아래에 내려만 두고 스크롤 못하도록?? 근데 어떤게 더 좋은방법인지 잘 모르겟다

무슨 뜻인지 좀 더 자세히 설명해줄 수 있어?

2023-07-27 10:49 UTC, Puterism commented on src/pages/NewQuestion/components/OptionSelect/OptionSelect.tsx
> +          <Spacing size={50} />
약간 Chakra UI 생각나네 ㅋㅋㅋ

2023-07-27 10:51 UTC, Puterism approved these changes
확인 완료! 수고 많았어!

2023-07-27 10:53 UTC, merged